### ISSUE TITLE
[BUG] runs abnormally

### ISSUE THREAD

**Issue by liyong7-tal** [eXamadeus/godaddypy#60]
version 2.5.1
from godaddypy import Account
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/lib/python3.7/site-packages/godaddypy/__init__.py", line 1, in <module>
    from .client import Client
  File "/Users/user/lib/python3.7/site-packages/godaddypy/client.py", line 8, in <module>
    from .account import Account
  File "/Users/user/lib/python3.7/site-packages/godaddypy/account.py", line 50, in <module>
    class Account(object):
  File "/Users/user/lib/python3.7/site-packages/godaddypy/account.py", line 103, in Account
    def __parse_configuration(self) -> Configuration | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

Code runs abnormally

**Comment by liyong7-tal** [comment]
python 3.7.3
